### ISSUE TITLE
Update annotations for PeptideProphet

### ISSUE THREAD

**Issue by nahmedraja** [Workflomics/containers#21]
For our new approach of cwltool pulling the containers itself, Peptideprophet should have three inputs:
 PeptideProphet_in_1:  
    type: File
    format: "http://edamontology.org/format_3655" # pepXML
  PeptideProphet_in_2:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  PeptideProphet_in_3: 
    type: File
    format: "http://edamontology.org/format_1929" # FASTA

where the mzML and FASTA are the files which genreated the pepXML file in previous step(s).

**Comment by vedran-kasalica** [comment]
FASTA format_1929 (as Protein sequence data_2976 data type) as input:

```
{
           "format_1915": ["http://edamontology.org/format_1929"],
           "data_0006": ["http://edamontology.org/data_2976"]
       }
