### ISSUE TITLE
Execute flag is not set on install scripts

### ISSUE THREAD

**Issue by 524D** [Workflomics/containers#7]
When building the docker container on Linux, I get some errors (see below). This is because the shell scripts in the “install” folder are don’t have the “execute” flag set. On Windows, this may not be obvious or needed. 

[This link](https://www.scivision.dev/git-windows-chmod-executable/) describes how to set the “execute” flag on Windows. 

Errors during Docker install:

```
Step 16/17 : RUN  for a in $tools;do /data/install/install_$a.sh; done
---> Running in 94bc76d08989
/bin/sh: 1: /data/install/install_mzdb-tools.sh: Permission denied
/bin/sh: 1: /data/install/install_tpp.sh: Permission denied
/bin/sh: 1: /data/install/install_maxquant.sh: Permission denied
/bin/sh: 1: /data/install/install_msqrob.sh: Permission denied
/bin/sh: 1: /data/install/install_sdrf-pipelines.sh: Permission denied
/bin/sh: 1: /data/install/install_raw2mzml.sh: Permission denied
/bin/sh: 1: /data/install/install_comet-ms.sh: Permission denied
/bin/sh: 1: /data/install/install_cwlrunner.sh: Permission denied
The command '/bin/sh -c for a in $tools;do /data/install/install_$a.sh; done' returned a non-zero code: 126
```

**Comment by nahmedraja** [comment]
Is the command
```
RUN chmod +x /data/install/*.sh && chmod +x /usr/local/scripts/*  && export PATH=$PATH:/usr/local/scripts
```
present in the Dockerfile not sufficient?

**Comment by nahmedraja** [comment]
Hello Rob,
Can you please delete the line:
`RUN chmod +x /data/install/*.sh && chmod +x /usr/local/scripts/*  && export PATH=$PATH:/usr/local/scripts`
from the Dockerfile and update the command to install the tools as:
`RUN  for a in $tools;do chmod +x /data/install/install_$a.sh &&  /data/install/install_$a.sh; done`

**Comment by 524D** [comment]
Hi Nauman, that works great!
Of course that the new `RUN` command must be moved 2 lines down, to the place where `$tools `is defined.

**Comment by nahmedraja** [comment]
Yes exactly. Thanks for testing. I will update the Dockerfile.

**Comment by 524D** [comment]
It now works correctly, so I'm closing the issue.
