### ISSUE TITLE
Error in install_tpp.sh

### ISSUE THREAD

**Issue by 524D** [Workflomics/containers#8]
There seems to be a small error in the `install_tpp.sh` script that is used to build the Docker image. 
The `sed` command near the end of the script produces the following message:

`sed: -e expression #1, char 14: unknown option to 's'
`

**Comment by nahmedraja** [comment]
The sed command is now removed from the install script. It was actually used to add ${INSTALL_DIR}/tpp/bin to $PATH. The paths to the TPP tools are now hardcoded to /usr/local/tpp/bin/<tool name> in the CWL files.
